### ISSUE TITLE
I found the launcher without drawer you were looking for

### ISSUE THREAD

**Issue by qw123wh** [GP2788/Launcher-NO-drawer#1]
Hello friend I found a launcher that is right for you without app drawer.  There he is.

https://github.com/renzhn/Lawndesk

It is also on the playstore

**Comment by zhubinsheng** [comment]
> Hello friend I found a launcher that is right for you without app drawer. There he is.
> 
> https://github.com/renzhn/Lawndesk
> 
> It is also on the playstore

hi
i run failed in android studio , did u work Lawndesk succ ?
